name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Clean
      run: rm -rf out

    - name: Test
      run: go test -v ./implementation_test.go
    
    - name: Build
      run: |
          mkdir -p out
          go build -o out/example ./cmd/example
          
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-example
        path: out/example
